feat: add observable entityType retrieval and corresponding schema validation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -124,6 +124,22 @@ jobs:
               sleep 2
             done
       - run:
+          name: Get SCP container ID and print logs
+          command: |
+            echo "Getting SCP container ID..."
+            SCP_CONTAINER_ID=$(docker ps -q --filter "name=scp")
+            echo "SCP container ID: $SCP_CONTAINER_ID"
+
+            # Check if the SCP container is running
+            if [ -z "$SCP_CONTAINER_ID" ]; then
+              echo "SCP container is not running. Cannot fetch logs."
+              exit 1  # Exit with an error if SCP container is not running
+            fi
+
+            # Print logs of the SCP container
+            echo "Printing SCP container logs..."
+            docker logs $SCP_CONTAINER_ID --tail=20000
+      - run:
           name: Wait for SCP Database Migration to Complete
           command: |
             echo "Waiting for SCP database migration to complete..."
