test docker issue

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -164,22 +164,22 @@ jobs:
             # Print logs of the SCP container
             echo "Printing SCP container logs..."
             docker logs $USER_CONTAINER_ID --tail=10000
-      - run:
-          name: Get SCP container ID and print logs
-          command: |
-            echo "Getting SCP container ID..."
-            SCP_CONTAINER_ID=$(docker ps -q --filter "name=scp")
-            echo "SCP container ID: $SCP_CONTAINER_ID"
+      # - run:
+      #     name: Get SCP container ID and print logs
+      #     command: |
+      #       echo "Getting SCP container ID..."
+      #       SCP_CONTAINER_ID=$(docker ps -q --filter "name=scp")
+      #       echo "SCP container ID: $SCP_CONTAINER_ID"
 
-            # Check if the SCP container is running
-            if [ -z "$SCP_CONTAINER_ID" ]; then
-              echo "SCP container is not running. Cannot fetch logs."
-              exit 1  # Exit with an error if SCP container is not running
-            fi
+      #       # Check if the SCP container is running
+      #       if [ -z "$SCP_CONTAINER_ID" ]; then
+      #         echo "SCP container is not running. Cannot fetch logs."
+      #         exit 1  # Exit with an error if SCP container is not running
+      #       fi
 
-            # Print logs of the SCP container
-            echo "Printing SCP container logs..."
-            docker logs $SCP_CONTAINER_ID --tail=10000
+      #       # Print logs of the SCP container
+      #       echo "Printing SCP container logs..."
+      #       docker logs $SCP_CONTAINER_ID --tail=10000
 
       - store_test_results:
           path: ./dev-ops/report
